// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgtunlyhcwwrghvetmfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNndHVubHloY3d3cmdodmV0bWZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNDgwNDEsImV4cCI6MjA2OTkyNDA0MX0.BQpyLSokruH9AP_hqWMt4v3MbDRcJzbQ98pzoXfXtkg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});